import * as _ from 'lodash';

import { IRole } from '../interfaces/roles.interface';
import * as permission from '../permissions';

export const OWNER_ROLE: IRole = {
  nameArabic: 'مالك',
  nameEnglish: 'Owner',
  permissions: [
    _.pick(permission.allBranch, ['value']),
    _.pick(permission.allCategory, ['value']),
    _.pick(permission.allDiscount, ['value']),
    _.pick(permission.allMerchant, ['value']),
    _.pick(permission.allOnboarding, ['value']),
    _.pick(permission.allOrder, ['value']),
    _.pick(permission.allProduct, ['value']),
    _.pick(permission.allProductGroup, ['value']),
    _.pick(permission.readRatingScale, ['value']),
    _.pick(permission.allReservation, ['value']),
    _.pick(permission.allTag, ['value']),
    _.pick(permission.allTicket, ['value']),
    _.pick(permission.allTicketTag, ['value']),
    _.pick(permission.allTransaction, ['value']),
    _.pick(permission.allTable, ['value']),
    _.pick(permission.allMerchantEmployee, ['value']),
    _.pick(permission.allRating, ['value']),
    // _.pick(permission.allMerchantEmployeeManager, ['value']),
    _.pick(permission.readBank, ['value']),
    _.pick(permission.readBranchGroup, ['value']),
    _.pick(permission.readMenuTemplate, ['value']),
    _.pick(permission.readMenuTemplateProduct, ['value']),
    _.pick(permission.readMenuTemplateProductGroup, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readCity, ['value']),
    _.pick(permission.allCoupon, ['value']),
  ],
};

export const MERCHANT_EMPLOYEE_ROLE: IRole = {
  nameArabic: 'موظف البائع',
  nameEnglish: 'Merchant Employee',
  permissions: [
    _.pick(permission.allBranch, ['value']),
    _.pick(permission.allDiscount, ['value']),
    _.pick(permission.readMerchant, ['value']),
    _.pick(permission.allOnboarding, ['value']),
    _.pick(permission.allOrder, ['value']),
    _.pick(permission.allProduct, ['value']),
    _.pick(permission.allProductGroup, ['value']),
    _.pick(permission.allReservation, ['value']),
    _.pick(permission.allTag, ['value']),
    _.pick(permission.allTicket, ['value']),
    _.pick(permission.allTicketTag, ['value']),
    _.pick(permission.allTransaction, ['value']),
    _.pick(permission.allTable, ['value']),
    _.pick(permission.readMerchantEmployee, ['value']),
    _.pick(permission.allRating, ['value']),
    _.pick(permission.readRatingScale, ['value']),
    _.pick(permission.readBranchGroup, ['value']),
    _.pick(permission.readMenuTemplate, ['value']),
    _.pick(permission.readMenuTemplateProduct, ['value']),
    _.pick(permission.readMenuTemplateProductGroup, ['value']),
    _.pick(permission.readCategory, ['value']),
    // _.pick(permission.readBank, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readCity, ['value']),
    _.pick(permission.allCoupon, ['value']),
  ],
};

export const CLIENT_ROLE: IRole = {
  nameArabic: 'العميل',
  nameEnglish: 'Client',
  permissions: [
    _.pick(permission.readBranch, ['value']),
    _.pick(permission.readDepartment, ['value']),
    _.pick(permission.readMerchant, ['value']),
    _.pick(permission.readProduct, ['value']),
    _.pick(permission.readProductGroup, ['value']),
    _.pick(permission.readTag, ['value']),
    _.pick(permission.readOnboarding, ['value']),
    _.pick(permission.readReservation, ['value']),
    _.pick(permission.updateReservation, ['value']),
    _.pick(permission.readCategory, ['value']),
    _.pick(permission.readTransaction, ['value']),
    _.pick(permission.readShoppexEmployee, ['value']),
    _.pick(permission.createOrder, ['value']),
    _.pick(permission.updateOrder, ['value']),
    _.pick(permission.deleteOrder, ['value']),
    _.pick(permission.readOrder, ['value']),
    _.pick(permission.readDiscount, ['value']),
    _.pick(permission.readTicketTag, ['value']),
    _.pick(permission.readTicketTagReason, ['value']),
    _.pick(permission.readRatingScale, ['value']),
    _.pick(permission.readTable, ['value']),
    _.pick(permission.readTag, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readTransaction, ['value']),
    _.pick(permission.allRating, ['value']),
  ],
};

export const ADMIN_ROLE: IRole = {
  nameArabic: 'الادمن',
  nameEnglish: 'Admin',
  permissions: [
    _.pick(permission.allBranch, ['value']),
    _.pick(permission.allBranchCategory, ['value']),
    _.pick(permission.allCategory, ['value']),
    _.pick(permission.allCountry, ['value']),
    _.pick(permission.allDiscount, ['value']),
    _.pick(permission.allMerchant, ['value']),
    _.pick(permission.allOnboarding, ['value']),
    _.pick(permission.allOrder, ['value']),
    _.pick(permission.allProduct, ['value']),
    _.pick(permission.allProductGroup, ['value']),
    _.pick(permission.allRatingScale, ['value']),
    _.pick(permission.allReservation, ['value']),
    _.pick(permission.allTag, ['value']),
    _.pick(permission.allTicket, ['value']),
    _.pick(permission.allTicketTag, ['value']),
    _.pick(permission.allTransaction, ['value']),
    _.pick(permission.allDepartment, ['value']),
    _.pick(permission.allCity, ['value']),
    _.pick(permission.allContent, ['value']),
    _.pick(permission.allBank, ['value']),
    _.pick(permission.allBranchGroup, ['value']),
    _.pick(permission.allMenuTemplate, ['value']),
    _.pick(permission.allMenuTemplateProduct, ['value']),
    _.pick(permission.allMenuTemplateProductGroup, ['value']),
    _.pick(permission.allTable, ['value']),
    _.pick(permission.allShoppexEmployee, ['value']),
    _.pick(permission.allMerchantEmployee, ['value']),
    _.pick(permission.allOwner, ['value']),
    _.pick(permission.allRating, ['value']),
    _.pick(permission.allCoupon, ['value']),

    _.pick(permission.allProviderOwner, ['value']),
    _.pick(permission.allDeliveryProvider, ['value']),
    _.pick(permission.allProviderEmployee, ['value']),
    _.pick(permission.allVehicle, ['value']),
    _.pick(permission.allVehicleModel, ['value']),
    _.pick(permission.allVehicleBrand, ['value']),
    _.pick(permission.allVehicleYear, ['value']),
    _.pick(permission.allDriver, ['value']),
    // _.pick(permission.allMerchantEmployeeManager, ['value']),
  ],
};

export const SHOPPEX_EMPLOYEE_ROLE: IRole = {
  nameArabic: 'موظف الادمن',
  nameEnglish: 'Shoppex Employee',
  permissions: [
    _.pick(permission.allBranch, ['value']),
    _.pick(permission.allCategory, ['value']),
    _.pick(permission.allCountry, ['value']),
    _.pick(permission.allDiscount, ['value']),
    _.pick(permission.allMerchant, ['value']),
    _.pick(permission.allOnboarding, ['value']),
    _.pick(permission.allOrder, ['value']),
    _.pick(permission.allProduct, ['value']),
    _.pick(permission.allProductGroup, ['value']),
    _.pick(permission.allRatingScale, ['value']),
    _.pick(permission.allReservation, ['value']),
    _.pick(permission.allTag, ['value']),
    _.pick(permission.allTicket, ['value']),
    _.pick(permission.allTicketTag, ['value']),
    _.pick(permission.allTransaction, ['value']),
    _.pick(permission.allShoppexEmployee, ['value']),
    _.pick(permission.allDepartment, ['value']),
    _.pick(permission.allCity, ['value']),
    _.pick(permission.allContent, ['value']),
    _.pick(permission.allBank, ['value']),
    _.pick(permission.allBranchGroup, ['value']),
    _.pick(permission.allMenuTemplate, ['value']),
    _.pick(permission.allMenuTemplateProduct, ['value']),
    _.pick(permission.allMenuTemplateProductGroup, ['value']),
    _.pick(permission.allTable, ['value']),
    _.pick(permission.allMerchantEmployee, ['value']),
    _.pick(permission.allOwner, ['value']),
    _.pick(permission.allRating, ['value']),
    _.pick(permission.allCoupon, ['value']),

    _.pick(permission.allProviderOwner, ['value']),
    _.pick(permission.allDeliveryProvider, ['value']),
    _.pick(permission.allProviderEmployee, ['value']),
    _.pick(permission.allVehicle, ['value']),
    _.pick(permission.allVehicleModel, ['value']),
    _.pick(permission.allVehicleBrand, ['value']),
    _.pick(permission.allVehicleYear, ['value']),
    _.pick(permission.allDriver, ['value']),
  ],
};

export const PROVIDER_OWNER_ROLE: IRole = {
  nameArabic: 'مزود التوصيل',
  nameEnglish: 'Provider Owner',
  permissions: [
    _.pick(permission.allDeliveryProvider, ['value']),
    _.pick(permission.allProviderEmployee, ['value']),
    _.pick(permission.allVehicle, ['value']),
    _.pick(permission.allDriver, ['value']),
    _.pick(permission.readVehicleModel, ['value']),
    _.pick(permission.readVehicleBrand, ['value']),
    _.pick(permission.readVehicleYear, ['value']),
    _.pick(permission.readOrder, ['value']),
    _.pick(permission.readTransaction, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readCity, ['value']),
  ],
};

export const PROVIDER_EMPLOYEE_ROLE: IRole = {
  nameArabic: 'موظف مزود التوصيل',
  nameEnglish: 'Provider Employee',
  permissions: [
    _.pick(permission.allDriver, ['value']),
    _.pick(permission.allVehicle, ['value']),
    _.pick(permission.readVehicleModel, ['value']),
    _.pick(permission.readVehicleBrand, ['value']),
    _.pick(permission.readVehicleYear, ['value']),
    _.pick(permission.readOrder, ['value']),
    _.pick(permission.readTransaction, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readCity, ['value']),
  ],
};

export const DRIVER_ROLE: IRole = {
  nameArabic: 'السائق',
  nameEnglish: 'Driver',
  permissions: [
    _.pick(permission.allVehicle, ['value']),
    _.pick(permission.readVehicleModel, ['value']),
    _.pick(permission.readVehicleBrand, ['value']),
    _.pick(permission.readVehicleYear, ['value']),
    _.pick(permission.readOrder, ['value']),
    _.pick(permission.updateOrder, ['value']),
    _.pick(permission.readCountry, ['value']),
    _.pick(permission.readCity, ['value']),
  ],
};
