export enum PermissionSlug {
  // Merchants Permissions
  UPDATE_MERCHANT = 'UPDATE_MERCHANT',
  READ_MERCHANT = 'READ_MERCHANT',
  READ_MERCHANTS = 'READ_MERCHANTS',

  // Category Permissions
  CREATE_CATEGORY = 'CREATE_CATEGORY',
  READ_CATEGORY = 'READ_CATEGORY',
  READ_CATEGORIES = 'READ_CATEGORIES',
  UPDATE_CATEGORY = 'UPDATE_CATEGORY',
  DELETE_CATEGORY = 'DELETE_CATEGORY',

  // Sysconfig Permissions
  CREATE_SysConfig = 'CREATE_SysConfig',
  READ_SysConfig = 'READ_SysConfig',
  READ_SysConfigS = 'READ_SysConfigS',
  UPDATE_SysConfig = 'UPDATE_SysConfig',
  DELETE_SysConfig = 'DELETE_SysConfig',

  // ClientAdres Permissions
  CREATE_ClientAdres = 'CREATE_ClientAdres',
  READ_ClientAdres = 'READ_ClientAdres',
  READ_ClientAdresS = 'READ_ClientAdresS',
  UPDATE_ClientAdres = 'UPDATE_ClientAdres',
  DELETE_ClientAdres = 'DELETE_ClientAdres',

  // Cities Permissions
  CREATE_CITY = 'CREATE_CITY',
  READ_CITY = 'READ_CITY',
  READ_CITIES = 'READ_CITIES',
  UPDATE_CITY = 'UPDATE_CITY',
  DELETE_CITY = 'DELETE_CITY',

  // Countries Permissions
  CREATE_COUNTRY = 'CREATE_COUNTRY',
  READ_COUNTRY = 'READ_COUNTRY',
  READ_COUNTRIES = 'READ_COUNTRIES',
  UPDATE_COUNTRY = 'UPDATE_COUNTRY',
  DELETE_COUNTRY = 'DELETE_COUNTRY',

  // Departments Permissions
  CREATE_DEPARTMENT = 'CREATE_DEPARTMENT',
  READ_DEPARTMENT = 'READ_DEPARTMENT',
  READ_DEPARTMENTS = 'READ_DEPARTMENTS',
  UPDATE_DEPARTMENT = 'UPDATE_DEPARTMENT',
  DELETE_DEPARTMENT = 'DELETE_DEPARTMENT',

  // Order Permissions
  CREATE_ORDER = 'CREATE_ORDER',
  READ_ORDER = 'READ_ORDER',
  READ_ORDERS = 'READ_ORDERS',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  // Permissions' Permissions
  READ_PERMISSION = 'READ_PERMISSION',
  READ_PERMISSIONS = 'READ_PERMISSIONS',

  // Product Permissions
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  READ_PRODUCT = 'READ_PRODUCT',
  READ_PRODUCTS = 'READ_PRODUCTS',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  // Branch Permissions
  CREATE_BRANCH = 'CREATE_BRANCH',
  READ_BRANCH = 'READ_BRANCH',
  READ_BRANCHS = 'READ_BRANCHS',
  UPDATE_BRANCH = 'UPDATE_BRANCH',
  DELETE_BRANCH = 'DELETE_BRANCH',

  // Branch Permissions
  CREATE_Onesignal = 'CREATE_Onesignal',
  READ_Onesignal = 'READ_Onesignal',
  READ_OnesignalS = 'READ_OnesignalS',
  UPDATE_Onesignal = 'UPDATE_Onesignal',
  DELETE_Onesignal = 'DELETE_Onesignal',

  // Dining Permissions
  CREATE_Dining = 'CREATE_Dining',
  READ_Dining = 'READ_Dining',
  READ_DiningS = 'READ_DiningS',
  UPDATE_Dining = 'UPDATE_Dining',
  DELETE_Dining = 'DELETE_Dining',

  // Product Category Permissions
  CREATE_PRODUCT_CATEGORY = 'CREATE_PRODUCT_CATEGORY',
  READ_PRODUCT_CATEGORY = 'READ_PRODUCT_CATEGORY',
  READ_PRODUCT_CATEGORIES = 'READ_PRODUCT_CATEGORIES',
  UPDATE_PRODUCT_CATEGORY = 'UPDATE_PRODUCT_CATEGORY',
  DELETE_PRODUCT_CATEGORY = 'DELETE_PRODUCT_CATEGORY',

  // Review Requests Permissions
  CREATE_REVIEW_REQUEST = 'CREATE_REVIEW_REQUEST',
  READ_REVIEW_REQUEST = 'READ_REVIEW_REQUEST',
  READ_REVIEW_REQUESTS = 'READ_REVIEW_REQUESTS',
  UPDATE_REVIEW_REQUEST = 'UPDATE_REVIEW_REQUEST',
  DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST',

  // Roles Permissions
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  READ_ROLES = 'READ_ROLES',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // Tag Permissions
  CREATE_TAG = 'CREATE_TAG',
  READ_TAG = 'READ_TAG',
  READ_TAGS = 'READ_TAGS',
  UPDATE_TAG = 'UPDATE_TAG',
  DELETE_TAG = 'DELETE_TAG',
}
