export const NOTIFICATION_CONTENT = {
  ar: {
    orderCreated: 'طلب جديد',
    orderCanceled: 'تم إلغاء الطلب',
    orderRejected: 'تم رفض الطلب',
    orderAccepted: 'تم قبول الطلب',
    orderReady: 'الطلب جاهز',
    orderOnWayToClient: 'الطلب في الطريق',
    orderArrivedToClient: 'المندول وصل للعميل',
    orderDeliveredToClient: 'تم التوصيل',
    orderClientNotRespond: 'عميل الطلب لا يرد',
    orderClientNotDelivered: 'لم يتم توصيل الطلب للعميل',
    orderDelivered: 'تم تسليم الطلب',
    requestCreated: 'طلب مراجعه',
    requestApproved: 'تمت الموافقة على الطلب',
    requestRejected: 'تم رفض الطلب',
    activeChangeStatus: 'تم تفعيل حسابك',
    blockChangeStatus: 'تم حظرك من قبل فريق الدعم',
    merchantCreated: 'متجر جديد',
    rejectedProduct: 'تم رفض المنتج',
    rejectedMerchant: 'تم رفض المتجر',
    rejectedBranch: 'تم رفض الفرع',
    rejectedBranchReservation: 'تم رفض الحجز للفرع',
    approvedProduct: 'تم قبول المنتج',
    approvedMerchant: 'تم قبول المتجر',
    approvedBranch: 'تم قبول الفرع',
    approvedBranchReservation: 'تم قبول الحجز للفرع',
    productQuantityWarning: 'تحذير هذا المنتج يقترب من النفاذ',
  },
  en: {
    orderCreated: 'Order Created',
    orderCanceled: 'Order Canceled',
    orderRejected: 'Order Rejected',
    orderAccepted: 'Order Accepted',
    orderReady: 'Order Ready',
    orderOnWayToClient: 'Order On Way To Clinet',
    orderArrivedToClient: 'Order Arrived To Client',
    orderDeliveredToClient: 'Order Delivered To Client',
    orderClientNotRespond: 'Order Client Not Respond',
    orderClientNotDelivered: 'Order Client Not Delivered',
    orderDelivered: 'Order Delivered',
    requestCreated: 'New Request',
    requestApproved: 'Request Approved',
    requestRejected: 'Request Rejected',
    activeChangeStatus: 'your account has been activated',
    blockChangeStatus: 'your account has been blocked',
    merchantCreated: 'New Merchant',
    rejectedProduct: 'Rejected Product',
    rejectedMerchant: 'Rejected Merchant',
    rejectedBranch: 'Rejected Branch',
    rejectedBranchReservation: 'Rejected Branch Reservation',
    approvedProduct: 'Approved Product',
    approvedMerchant: 'Approved Merchant',
    approvedBranch: 'Approved Branch',
    approvedBranchReservation: 'Approved Branch Reservation',
    productQuantityWarning: 'Product Quantity Warning',
  },
};
